
spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        cache:
          use_second_level_cache: true
          use_query_cache: true
          use_structured_entries: true
          region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
      javax:
        persistence.sharedCache.mode: ENABLE_SELECTIVE
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    mongodb:
       host: localhost
       port: 27017
       database: ticket_booking
  datasource:
    url: jdbc:postgresql://localhost:5432/ticket_booking
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

properties:
  migration_enabled: true
  main_db: mongo

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace
    net:
      sf:
        ehcache=debug:
server:
  port: 8082